### ISSUE TITLE
Passive flowers dont actually work

### ISSUE THREAD

**Issue by Fortist** [TheIcyOne/Easy-Pickings#10]
I see the particles, and It took a while to find out that you cant connect them with a wand (Should be in the description, tbh)
But I didnt find out how exactly do these things work, if they work at all, since placing them next to a mana pool did nothing and a mana spreader did nothing. (I have a mod that shows how much mana something has and both Mana spreader and pool gained nothing after several minutes, despite also changing the rate to 100)
So, Im gonna guess they dont work.

Also, as a side note, some configuration for the unstable goo, change the explosion time and what not.

**Comment by TheIcyOne** [comment]
They should slowly fill your pools and/or spreaders, but when I say slowly I mean incredibly slowly. Like 10 mana/day slow.

I'll look into the unstable goo changes.

**Comment by krusynth** [comment]
Hi, did the flowers break since the last release?  I've got Botania r1.10-363 and EasyPickings 1.7.1, but no mana is being generated no matter how high I crank the settings on the flowers. I tested my setup with an Endoflame and it works as expected.

My config looks like this (though my local file is correctly named with `.cfg`, not `.txt` as required by GitHub here): [Easy Configgings.txt](https://github.com/TheIcyOne/Easy-Pickings/files/6683360/Easy.Configgings.txt) 

Thanks!

**Comment by TheIcyOne** [comment]
So I haven't touched this mod in years, but from a quick glance the way the fake dayblooms work is by occasionally, on random ticks, searching for nearby mana pools and filling them by whatever value is in the config. It only checks 1 block in a 10x10x10 cube around it 1/20 of the time, so you'd have better success setting the random ticks gamerule to something absurd and placing a few pools around it. I'm also not sure how botania behaves if you try to overfill pools, so you may be missing out by setting the config value too high.
Try placing 1-2 dayblooms surrounded by a load of pools, then putting /gamerule randomTickSpeed to something like 1000. You should start to see mana.
